### ISSUE TITLE
I have one account that always says "Encrypted"

### ISSUE THREAD

**Issue by Brianetta** [Authenticator-Extension/Authenticator#103]
Even when I delete the account, and add it manually, it immediately says `Encrypted` and asks me for my password. The secret is formatted `xxxx xxxx xxxx xxxx` where `x` is any lower case letter or a digit.

**Comment by Sneezry** [comment]
Can you confirm is the secret is HEX format or Base32 format? HEX contains 0-9 and a-f, while Base32 contains a-z and 2-7. Also, is the secret's length is 16 (without spaces)?

**Comment by Brianetta** [comment]
It's base32. There's at least one z in it. Yes, 16 in four groups of four.

**Comment by Brianetta** [comment]
I have reset 2FA to a new key. The problematic key is:

```yaml
  "1b0c21ad1ec44264f665708ef82dae84": {
    "account": "brian@ppcis.org",
    "counter": 0,
    "encrypted": false,
    "hash": "1b0c21ad1ec44264f665708ef82dae84",
    "index": 19,
    "issuer": "Discord",
    "secret": "p5s7 k2in z3mj oqfg",
    "type": "totp"
  },
```
