### ISSUE TITLE
Can't scan a barcode (which scanned OK when use Google Authenticator Android App) 

### ISSUE THREAD

**Issue by longtth** [Authenticator-Extension/Authenticator#516]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

I can't scan my company's authenticator QR Code, the site say: `Unrecognized QR code.` 

the qrcode image: 
![image](https://user-images.githubusercontent.com/1010849/88371129-a6d96700-cdbd-11ea-9700-08904c7787c2.png)

**Platform:** Windows 10 1909 64bit 
 - Browser: Chrome 
 - Browser Version: 84.0.4147.89 

** log ** 

```yml
popup.js:35 Add Dragula plugin: Object
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/dist/popup.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/dist/argon.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/css/popup.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
